---
title: The Ginger Techie
email: thegingertechie@gmail.com
author: Kara Wolter
author_github: KaraWolter
description: |
  A blog where I talk about the technology and anything else I'm interested in.
baseurl: "/"
permalink: ":slug"
url: http://thegingertechie.com
paginate: 12
github:
  user: KaraWolter
  repository: KaraWolter.github.io
  url: http://thegingertechie.com
  status: true
  avatar: https://avatars1.githubusercontent.com/u/5532043?v=3&u=00d95a0d6b01d35811383ee28b140a142cb98400&s=400
home_bgfile: home.png
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
- jekyll-paginate
exclude:
- vendor
# Google
google_analytics: UA-98468743-1
